"""User-facing names, descriptions, and sections for known cloth fields."""

CLP_HEADER_UI = {
    "dataVersion_": ("数据版本", "文件结构版本；通常不需要修改"),
    "id_": ("求解组 ID", "CLP 求解组的原始编号"),
    "reboundRate_": ("回弹率", "布料恢复运动的回弹比例"),
    "airResistance_": ("空气阻力", "整体运动阻尼"),
    "windResistance_": ("风阻", "对风力响应的阻尼"),
    "stretchy_": ("整体拉伸", "纵向结构的拉伸参数"),
    "stretchyHInner_": ("纵向内侧拉伸", "纵向内部约束的拉伸参数"),
    "stretchyWOuter_": ("横向外侧拉伸", "横向外缘约束的拉伸参数"),
    "stretchyWInner_": ("横向内侧拉伸", "横向内部约束的拉伸参数"),
    "hitAdjustRate_": ("碰撞修正率", "碰撞后位置修正的混合比例"),
    "originalRate_": ("原姿势保持率", "向原始姿势恢复的组级比例"),
    "simulationRate4CS_": ("过场模拟倍率", "过场或特殊场景使用的模拟倍率"),
    "localGravityRate_": ("局部重力强度", "局部重力的作用比例"),
    "localGravityBlendRate_": ("局部重力混合", "局部重力与基础重力的混合比例"),
    "teleportResetDis_": ("瞬移重置距离", "移动超过此距离时重置布料状态"),
    "floorHeight_": ("地面高度", "启用地面碰撞时使用的高度"),
    "windRateFromBack_": ("背面风力比例", "从布料背面受风时的倍率"),
    "moveSpdRate_": ("移动速度影响", "角色移动速度对布料的影响比例"),
    "shortHairadjust_": ("短发修正", "短发布料的专用修正参数；公式尚未完全确认"),
    "airResistance4Chest_": ("胸部空气阻力", "胸部专用空气阻力覆盖"),
    "localGravityRate4Chest_": ("胸部局部重力", "胸部专用局部重力覆盖"),
    "collisionLevels_": ("碰撞迭代层级", "碰撞处理层级；精确公式尚未确认"),
    "childTraceLevels_": ("子节点追踪层级", "向子节点传播或追踪的层级"),
    "gravityPartsNo_": ("重力部件编号", "局部重力部件选择；负值具有特殊含义"),
    "bParentGravity_": ("继承父级重力", "使用父级的重力设置"),
    "fixAxis_": ("固定轴模式", "轴固定模式；枚举含义尚未完全确认"),
    "bNoStretchy_": ("禁用拉伸", "禁用该组的拉伸行为"),
    "bWorldWindEnable_": ("启用世界风", "接收世界空间风力"),
    "bAtCenter_": ("碰撞中心模式", "碰撞中心相关开关；精确作用尚未确认"),
    "atDensity_": ("碰撞密度", "碰撞采样密度或级别；精确作用尚未确认"),
    "localGravityType_": ("局部重力类型", "局部重力模式编号"),
    "localGravityBlendFlg_": ("混合局部重力", "启用局部重力混合"),
    "bLateAddMode_": ("延迟叠加模式", "在较晚阶段叠加布料结果"),
    "bNotReCalc_": ("禁止重新计算", "跳过部分重新计算流程"),
    "bHitFloorEnable_": ("启用地面碰撞", "启用 floorHeight_ 地面限制"),
    "bBlendRateLast_": ("末端混合率模式", "末端节点混合方式；精确作用尚未确认"),
    "useCollisionFlags_": ("使用的碰撞层", "位掩码：bit N 对应 CLH 层 N"),
    "bIsUseWindPowUp_": ("使用强化风力", "允许特殊状态提高风力"),
    "bChestParamAvailable_": ("启用胸部参数", "启用胸部专用空气阻力与局部重力"),
}

CLP_HEADER_GROUPS = (
    ("基础求解", ("reboundRate_", "airResistance_", "windResistance_", "originalRate_", "simulationRate4CS_")),
    ("拉伸与碰撞", ("stretchy_", "stretchyHInner_", "stretchyWOuter_", "stretchyWInner_", "hitAdjustRate_", "collisionLevels_", "childTraceLevels_")),
    ("重力与地面", ("gravityPartsNo_", "bParentGravity_", "localGravityType_", "localGravityRate_", "localGravityBlendFlg_", "localGravityBlendRate_", "bHitFloorEnable_", "floorHeight_", "teleportResetDis_")),
    ("风力与移动", ("bWorldWindEnable_", "windRateFromBack_", "bIsUseWindPowUp_", "moveSpdRate_", "shortHairadjust_")),
    ("特殊模式", ("fixAxis_", "bNoStretchy_", "bAtCenter_", "atDensity_", "bLateAddMode_", "bNotReCalc_", "bBlendRateLast_", "bChestParamAvailable_", "airResistance4Chest_", "localGravityRate4Chest_")),
)
